project:
  name: 正式环境


spring:
  datasource:
    url: jdbc:mysql://47.93.221.91/online_program?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #自动创建和更新数据表
    show-sql: true     # 控制台显示sql语句
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8
