spring:
  profiles:
    active: test
#  mvc:
#    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/,classpath:/templates/

server:
  port: 8082

logging:
  level:
    com.example: ++
#  file:
  path: ./logger/
#server:
#  servlet:
#    context-path: /crud
