spring:
  profiles:
    active: test
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    com.example: debug
#  file:
  path: ./logger/
#server:
#  servlet:
#    context-path: /crud

devtools:
  restart:
    enabled=true: