# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 登录
POST http://127.0.0.1:8080/api/user/login/
Content-Type: application/json

{
  "data": {
    "user_name":"18322693235",
    "pwd": "1234569"
  }
}

### 用户创建
POST http://127.0.0.1:8080/api/user/create/
Content-Type: application/json

{
  "user_name":"18322693235",
  "age":18,
  "desc": "1239",
  "birthday": "2018-12-09 16:00:00.00",
  "pwd": "1234569",
  "description": "1235655559",
  "email": "790872612@qq.com",
  "tel" : "18322693237"
}

###