# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 登录
POST http://127.0.0.1:8080/api/user/login/
Content-Type: application/json

{
  "data": {
    "tel":"18322693235",
    "pwd": "123456"
  }
}

### 用户创建
POST http://127.0.0.1:8080/api/user/create/
Content-Type: application/json

{
  "user_name":"乔乔",
  "age":18,
  "desc": "1239",
  "birthday": "2019-05-20 13:14:00.00",
  "pwd": "123456",
  "description": "后端开发程序员",
  "email": "790872612@qq.com",
  "tel" : "18322693235",
  "sex": true
}

###

POST http://127.0.0.1:8080/api/user/list/simple/
Content-Type: application/json

{
  "data": {
    "page": 1,
    "size": 10
  }
}

###