# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 登录
POST http://127.0.0.1:8080/api/user/login/
Content-Type: application/json

{
  "data": {
    "tel":"007",
    "pwd": "123456"
  }
}

### 用户创建
POST http://127.0.0.1:8080/api/user/create/
Content-Type: application/json

{
  "user_name":"admin",
  "age":99,
  "desc": "管理员",
  "birthday": "2019-05-20 13:14:00.00",
  "pwd": "123456",
  "description": "管理员",
  "email": "790872612@qq.com",
  "tel" : "007",
  "sex": true,
  "is_super": true
}

###
#{
#  "user_name":"小y",
#  "age":18,
#  "desc": "1239",
#  "birthday": "2019-05-20 13:14:00.00",
#  "pwd": "123456",
#  "description": "Python程序员",
#  "email": "790872612@qq.com",
#  "tel" : "18322693299",
#  "sex": true,
#  "is_super": false
#}

###

POST http://127.0.0.1:8080/api/user/list/simple/
Content-Type: application/json

{
  "data": {
    "page": 3,
    "size": 2
  }
}

###

POST http://127.0.0.1:8080/api/user/info/by/tel/
Content-Type: application/json

{
  "data": {
    "token": "e1ffe11015e74cda87e7e8e9b36c18a9",
    "tel": "18322693278"
  }
}

###